name: Tests

on: 
  push:
#  workflow_call:
#    inputs:
#      linux_exclude_swift_versions: "[{\"swift_version\": \"5.9\"}, {\"swift_version\": \"5.10\"}, {\"swift_version\": \"6.0\"}]"
      #linux_swift_versions: ["6.2"]
      #windows_swift_versions: []


jobs:
  tests:
    name: tests
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.10
    with:
      linux_swift_versions: "[\"6.2\"]"
      windows_swift_versions: "[]"

