name: Tests

on: 
  push:
  workflow_call:
    inputs:
      linux_swift_versions: "[\"6.2\"]"
      windows_swift_versions: "[]"


jobs:
  tests:
    name: tests
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.10

